export const welcomeStickers = [
  // Chitanda
  'CAACAgUAAxkBAAOBYrigMToAAd9-jTAHZe2WTUG65VllAALEAQACtCJJVkh8ZLJ1xpfYKQQ',
  'CAACAgUAAxkBAAODYrihj_EwqS0jutEuv-VdUTRqryEAAiIDAAK-E1BWlyEpYA16HKUpBA',
  'CAACAgUAAxkBAAOiYriiLMw8w0JiaNZAxQl-g9nY31sAApsCAAJecFFWr74zuF80qScpBA',
  'CAACAgUAAxkBAAOkYriiPG8JY2m8CMhzuxkDJfp6-3kAAuoBAAKFWvlVRwrSOZPxPg4pBA',
  'CAACAgUAAxkBAAOmYriiPvXaeNABQtS8anWhXmwXnjgAAroBAALScvhVpPq83zetYjApBA',
  // Kanna
  'CAACAgIAAxkBAAOqYriieiGifdcmkk6-RJw3kJcrNX4AAhQRAAIu00BLCKNX3hFWxl4pBA',
  'CAACAgIAAxkBAAOsYriie2elmWINgHiavbLVniowlKcAAuwPAALKNTlLvvJ0T2tf1mUpBA',
  'CAACAgIAAxkBAAOuYriihLPs8LaCzIstlqAeQmp69ywAAuQSAAKjFUFLaA3ddosb7DMpBA',
  // Оляшовские
  'CAACAgIAAxkBAAOoYriiX5unJqZwFFuqQRzIGu2zy_EAAkkAA4lUuRpcFgdOqlMeZCkE',
]
